name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build solution
        run: dotnet build

      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Install Playwright browsers
        run: playwright install chromium

      - name: Start ASP.NET Core application
        run: |
          nohup dotnet run --project ./WebApplication1 --urls http://localhost:5176 > output.log 2>&1 &
        working-directory: ./

      - name: Wait for application to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:5176 > /dev/null; then
              echo "Application is up!"
              break
            fi
            echo "Waiting for the application to start..."
            sleep 2
          done

      - name: Display application logs
        run: cat output.log

      - name: Run Playwright tests
        run: dotnet test

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestRecords
          path: /home/runner/work/UITester/UITester/TestRecords