name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build & Install
        run: dotnet build
      - name: cli
        run: dotnet tool install --global Microsoft.Playwright.CLI
      - name: install playwright
        run: playwright install chromium
      - name: Run your tests
        run: dotnet test
      - name: Upload Test Records
        uses: actions/upload-artifact@v3
        with:
          name: TestRecords
          path: ./UITester/UITester/TestRecords