name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build solution
        run: dotnet build

      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Install Playwright browsers
        run: playwright install chromium

      - name: Start ASP.NET Core application
        run: |
          nohup dotnet run --project ./Path/To/Your/WebProject > output.log 2>&1 &
        working-directory: ./

      - name: Wait for application to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: http://localhost:5176
          timeout: 60

      - name: Run Playwright tests
        run: dotnet test

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TestRecords
          path: /home/runner/work/UITester/UITester/TestRecords
